"""map/adjacency_rules.txt writer.

Reference: Reference/Map modding.txt lines 504-520.
- Required UTF-8 no BOM (line 505)
- Multiple adjacency_rule = { ... } blocks, each block independent
- LF line feed"""

from __future__ import annotations

import os


def write_adjacency_rules_txt(output_dir: str, rule_mgr=None) -> None:
    """Generate map/adjacency_rules.txt.

    rule_mgr: AdjacencyRuleManager instance. Writes an empty file when None or empty (HOI4 accepts empty)."""
    d = os.path.join(output_dir, "map")
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "adjacency_rules.txt")

    parts: list[str] = []
    parts.append("# Auto-generated by HOI4 MOD Maker")
    parts.append("# Adjacency rules — passage conditions for straits/canals.")
    parts.append("")

    if rule_mgr is not None:
        for rule in rule_mgr.get_all():
            parts.append(rule.to_block())
            parts.append("")

    content = "\n".join(parts) + "\n"
    with open(path, "wb") as f:
        f.write(content.encode("utf-8"))
