"""map/railways.txt writer.

Reference: Reference/Map modding.txt lines 534-540
Format: Level Count ProvId1 ProvId2 ... (space separated, one per line)
- An empty file is retained when no valid route or proposal exists; the
  export validation gate then reports missing logistics.
- No BOM, LF line feed

Export logic: Explicit railway paths are retained; single-province placeholders generated by province brushes are connected according to map adjacency."""

from __future__ import annotations

import os
import numpy as np

from domain.managers.railway import adjacent_railway_segments


def write_railways_txt(
    output_dir: str,
    railway_mgr=None,
    province_map: np.ndarray | None = None,
    fallback_pid: int = 1,
) -> None:
    """Generate map/railways.txt.

    Explicit paths are output in original order. The province brush’s ``[pid, pid]`` placeholder entry is used
    province_map derives adjacent joins."""
    d = os.path.join(output_dir, "map")
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "railways.txt")

    lines: list[str] = []

    if railway_mgr is not None and province_map is not None:
        lines = _build_manager_railway_lines(railway_mgr, province_map)

    # If there is no authored/brush route, make at most a valid adjacent pair
    # proposal.  Never emit the old ``pid pid`` self-loop placeholder.  When
    # no distinct pair can be proposed, leave the file empty so the export
    # validation gate reports missing logistics instead of hiding it.
    if not lines:
        pair = first_distinct_adjacent_pair(province_map)
        if pair is not None:
            lines.append(f"1 2 {pair[0]} {pair[1]}")

    content = "\n".join(lines) + ("\n" if lines else "")
    with open(path, "wb") as f:
        f.write(content.encode("utf-8"))


def first_distinct_adjacent_pair(
    province_map: np.ndarray | None,
    allowed_provinces: set[int] | None = None,
) -> tuple[int, int] | None:
    """Return the first deterministic distinct raster-adjacent province pair."""
    if province_map is None:
        return None
    pm = np.asarray(province_map)
    if pm.ndim != 2:
        return None
    for first_array, second_array in (
        (pm[:-1, :], pm[1:, :]),
        (pm[:, :-1], pm[:, 1:]),
    ):
        mask = (first_array != second_array) & (first_array > 0) & (second_array > 0)
        if allowed_provinces is not None:
            mask &= np.isin(first_array, tuple(allowed_provinces))
            mask &= np.isin(second_array, tuple(allowed_provinces))
        ys, xs = np.where(mask)
        if len(ys):
            first = int(first_array[ys[0], xs[0]])
            second = int(second_array[ys[0], xs[0]])
            return (min(first, second), max(first, second))
    return None


def _build_railway_lines(
    levels: dict[int, int],
    province_map: np.ndarray,
) -> list[str]:
    """Convert province level mapping to rail lines for adjacent province pairs.

    Algorithm: Scan province_map to find adjacent province pairs,
    If both provinces have railway levels, generate a railway with level=min.
    Output after deduplication."""
    return [
        f"{level} 2 {first} {second}"
        for level, first, second in adjacent_railway_segments(levels, province_map)
    ]


def _build_manager_railway_lines(railway_mgr, province_map: np.ndarray) -> list[str]:
    """Preserve authored paths and expand only brush placeholders."""
    entries = railway_mgr.get_all()
    present = set(int(p) for p in np.unique(province_map) if p > 0)
    explicit = [
        entry for entry in entries
        if len(entry.province_ids) >= 2
        and len(set(entry.province_ids)) >= 2
        and all(pid in present for pid in entry.province_ids)
    ]
    lines = [entry.to_line() for entry in explicit]
    explicit_pairs = {
        tuple(sorted((a, b)))
        for entry in explicit
        for a, b in zip(entry.province_ids, entry.province_ids[1:])
    }
    placeholders = {
        entry.province_ids[0] for entry in entries
        if entry.province_ids and len(set(entry.province_ids)) == 1
        and bool(getattr(entry, "brush_placeholder", False))
    }
    if placeholders:
        for line in _build_railway_lines(railway_mgr.province_levels(), province_map):
            parts = line.split()
            a, b = int(parts[2]), int(parts[3])
            if (a in placeholders or b in placeholders) and (a, b) not in explicit_pairs:
                lines.append(line)
    return lines
