"""map/railways.txt writer.

Reference: Reference/Map modding.txt lines 534-540
Format: Level Count ProvId1 ProvId2 ... (space separated, one per line)
- Cannot be empty (CLAUDE.md constraint, empty file will collapse)
- No BOM, LF line feed

Export logic: Explicit railway paths are retained; single-province placeholders generated by province brushes are connected according to map adjacency."""

from __future__ import annotations

import os
import numpy as np


def write_railways_txt(
    output_dir: str,
    railway_mgr=None,
    province_map: np.ndarray | None = None,
    fallback_pid: int = 1,
) -> None:
    """Generate map/railways.txt.

    Explicit paths are output in original order. The province brush’s ``[pid, pid]`` placeholder entry is used
    province_map derives adjacent joins."""
    d = os.path.join(output_dir, "map")
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "railways.txt")

    lines: list[str] = []

    if railway_mgr is not None and province_map is not None:
        lines = _build_manager_railway_lines(railway_mgr, province_map)

    # Must be non-empty
    if not lines:
        lines.append(f"1 2 {fallback_pid} {fallback_pid}")

    content = "\n".join(lines) + "\n"
    with open(path, "wb") as f:
        f.write(content.encode("utf-8"))


def _build_railway_lines(
    levels: dict[int, int],
    province_map: np.ndarray,
) -> list[str]:
    """Convert province level mapping to rail lines for adjacent province pairs.

    Algorithm: Scan province_map to find adjacent province pairs,
    If both provinces have railway levels, generate a railway with level=min.
    Output after deduplication."""
    # Find all adjacent province pairs (vectorized, no pixel-by-pixel loop)
    pm = province_map
    pairs: set[tuple[int, int]] = set()

    # vertically adjacent
    diff_v = pm[:-1, :] != pm[1:, :]
    ys, xs = np.where(diff_v)
    for i in range(len(ys)):
        a, b = int(pm[ys[i], xs[i]]), int(pm[ys[i] + 1, xs[i]])
        if a > 0 and b > 0 and a in levels and b in levels:
            pair = (min(a, b), max(a, b))
            pairs.add(pair)

    # horizontally adjacent
    diff_h = pm[:, :-1] != pm[:, 1:]
    ys, xs = np.where(diff_h)
    for i in range(len(ys)):
        a, b = int(pm[ys[i], xs[i]]), int(pm[ys[i], xs[i] + 1])
        if a > 0 and b > 0 and a in levels and b in levels:
            pair = (min(a, b), max(a, b))
            pairs.add(pair)

    # Generate railway lines: one for each pair of adjacent provinces, level = min (both levels)
    lines: list[str] = []
    for a, b in sorted(pairs):
        lvl = min(levels[a], levels[b])
        lines.append(f"{lvl} 2 {a} {b}")

    return lines


def _build_manager_railway_lines(railway_mgr, province_map: np.ndarray) -> list[str]:
    """Preserve authored paths and expand only brush placeholders."""
    entries = railway_mgr.get_all()
    present = set(int(p) for p in np.unique(province_map) if p > 0)
    explicit = [
        entry for entry in entries
        if len(entry.province_ids) >= 2
        and len(set(entry.province_ids)) >= 2
        and all(pid in present for pid in entry.province_ids)
    ]
    lines = [entry.to_line() for entry in explicit]
    explicit_pairs = {
        tuple(sorted((a, b)))
        for entry in explicit
        for a, b in zip(entry.province_ids, entry.province_ids[1:])
    }
    placeholders = {
        entry.province_ids[0] for entry in entries
        if entry.province_ids and len(set(entry.province_ids)) == 1
    }
    if placeholders:
        for line in _build_railway_lines(railway_mgr.province_levels(), province_map):
            parts = line.split()
            a, b = int(parts[2]), int(parts[3])
            if (a in placeholders or b in placeholders) and (a, b) not in explicit_pairs:
                lines.append(line)
    return lines
