"""Application version and release history."""

VERSION = "1.3.4"
VERSION_DATE = "2026-07-11"

CHANGELOG = {
    "1.3.4": {
        "date": "2026-07-11",
        "changes": [
            "🚨 Fixed the strategic-region export preflight, including automatic splitting of disconnected regions.",
            "Fixed states split across strategic regions by merging their export data back into one region and flagging enclaves.",
            "Added a command to resynchronize provincial terrain from the visual terrain layer with confirmation and undo support.",
            "Corrected terrain-mode help text so it no longer claims that visual painting changes provincial gameplay terrain.",
            "Made the MOD validator read all files as UTF-8 so non-ASCII content cannot interrupt validation.",
            "Made language settings consistently use UTF-8 and removed the platform-code-page failure mode.",
            "Fixed the world-normal regeneration path after mountain downgrades.",
            "Added post-export checks for cross-region states, duplicate province assignments, and missing strategic-region IDs.",
        ],
    },
    "1.3.3": {
        "date": "2026-07-10",
        "changes": [
            "🚨 Fixed packaged builds crashing when switching to Logistics, Continents, Provincial Terrain, or Preview.",
            "Fixed undo for territory assignment so the previous country is restored.",
            "Fixed province terrain selection reporting an error even though the edit succeeded.",
            "Separated name labels for disconnected territories so labels do not cross neighboring countries.",
            "Added separate country information and territory-assignment modes.",
            "Added optional city names when setting victory points.",
            "Added a night-preview toggle with city lights.",
            "Added direct save and Save As actions while preserving the first-save prompt for new projects.",
            "Added fog-of-war water-specular and city-light assets to exported MODs.",
            "Aligned preview water colors with exported water colormaps.",
        ],
    },
    "1.3.2": {
        "date": "2026-07-06",
        "changes": [
            "🚨 Fixed new projects incorrectly filling the river layer with source markers.",
            "Fixed the river brush using a stale brush size and drawing rivers wider than one pixel.",
            "Added scrolling to state-detail tabs so buildings and multiple victory points remain accessible.",
            "Added HOI4-style state and country labels to the map.",
            "Added political map preview shading.",
            "Added resplitting of provinces inside a selected state without changing country ownership.",
            "Added a shortcut from a province to its state-detail editor.",
            "Added terrain underlay support to the river editor.",
            "Added river validation to export preflight for missing sources, diagonal joins, and excessive width.",
            "Vectorized map labels and river validation for large-map responsiveness.",
            "Made the application and generated output English-only.",
        ],
    },
    "1.3.1": {
        "date": "2026-07-05",
        "changes": [
            "Reorganized the reference-map card and added a one-click vanilla reference action.",
            "Added a reference-image positioning mode with drag, wheel zoom, and ESC to exit.",
            "Removed the stretching Fill button and changed vanilla reference loading to centered aspect-ratio scaling.",
            "Added a confirmation before painting land or sea after provinces already exist.",
            "Added live brush-ring previews to terrain, height, and density tools.",
            "Prevented the sidebar from scrolling beyond the active page content.",
            "Redesigned choice dialogs to avoid clipped text and excessive card spacing.",
            "Reordered height generation around the normal workflow: generate, infer from terrain, then refine.",
            "Removed unsupported height import, local height-lasso, and local province-regeneration controls.",
        ],
    },
    "1.3.0": {
        "date": "2026-07-04",
        "changes": [
            "Added a game-style preview using vanilla terrain textures, lighting, and climate tinting.",
            "Added a read-only vanilla-map reference project.",
            "Added one-click realistic heightmap generation with coast shelves and mountain chains.",
            "Added climate-based terrain detailing with jungle, desert, forest, and snowline patterns.",
            "Improved the mountain-line tool to create connected ridges with peaks and passes.",
            "Added full regional height regeneration with smooth edges and no changes outside the selection.",
            "Added optional export-time compaction for province ID gaps without modifying the project.",
            "Fixed imported MOD and vanilla maps showing empty country lists and missing country metadata.",
            "Improved preview scaling quality.",
            "Fixed export compaction for railways, supply hubs, adjacency rules, continents, and provincial terrain.",
            "Made supported_version follow the locally detected HOI4 version.",
            "Reduced heightmap generation time from more than 10 seconds to under 10 seconds in the benchmark.",
            "Registered render dispatch, generator protocols, and readiness checks as services.",
        ],
    },
    "1.2.0": {
        "date": "2026-05-19",
        "changes": [
            "Made translation maintenance explicit through audit and key-generation tools.",
            "Added undo support for continent operations and province search navigation.",
            "Added an independent descriptor-export switch.",
            "Fixed several crashes and isolated generated names from vanilla namespaces.",
            "Fixed packaged qdarktheme data collection.",
            "Fixed strategic-region, province-merge, and incremental-generation edge cases.",
            "Fixed state selection using the correct country-owner accessor.",
            "Fixed export size limits, import traps, and transform-copy behavior.",
            "Completed the visual audit across all thirteen editor pages.",
            "Unified the continent page with the other editor pages.",
            "Fixed font metrics and sidebar sizing for the English interface.",
            "Fixed three tests and added two English localization keys.",
        ],
    },
    "1.1.2": {
        "date": "2026-04-27",
        "changes": [
            "Added three-layer state-mode overlays that distinguish country ownership.",
            "Blended state and country colors while preserving adjacent-state contrast.",
            "Added three-pixel country borders between assigned countries.",
            "Added warm highlighting for all states owned by the selected country.",
        ],
    },
    "1.1.0": {
        "date": "2026-04-26",
        "changes": [
            "🚨 Stability update for HOI4 1.18 (Case Green).",
            "Fixed automatic vanilla continent definitions for portrait safety.",
            "Fixed division-name country scoping.",
            "Compacted state IDs to a consecutive 1..N range.",
            "Fixed character-file UTF-8 BOM handling and stable ID-based names.",
            "Fixed country-history filenames to use the country tag.",
            "Added common/on_actions to replacement paths.",
            "Automatically split disconnected strategic regions.",
            "Made strategic-region generation thirteen times faster in the benchmark.",
            "Added state and country deletion with confirmation and undo.",
            "Added terrain-based height inference.",
            "Added country-border highlighting.",
            "Added heightmap and provincial-terrain underlay switching.",
            "Added drag assignment for provincial terrain.",
            "Added continuous terrain brushing while holding the mouse button.",
            "Added the complete seven-resource vanilla list, including coal.",
            "Added confirmations for nine destructive operations.",
            "Stopped visual terrain edits from overwriting manually selected provincial terrain.",
            "Added distance-field ocean shading, brighter land heights, snowy mountains, and coast beaches.",
            "Improved terrain color saturation.",
            "Added the zz_ localization prefix so generated state entries override vanilla entries.",
            "Kept exported localization data in UTF-8 without ASCII-only restrictions.",
        ],
    },
    "1.0.0": {
        "date": "2026-04-18",
        "changes": [
            "Released version 1.0.",
            "Completed the original localization pass for the user interface.",
            "Made language selection take effect without a restart.",
            "Fixed the New Project dialog OK button rendering.",
        ],
    },
    "1.0.2-beta": {
        "date": "2026-04-16",
        "changes": [
            "Fixed invalid river palette indices and diagonal river pixels.",
            "Added a recovery path for coastal provinces without a naval-base spawn point.",
            "Changed heightmap generation to a distance field for smoother coasts.",
            "Prevented automatic terrain generation from extending into sea pixels.",
            "Limited provincial-terrain inference to genuine land provinces.",
            "Added an independent provincial-terrain display mode.",
            "Synchronized generated visual terrain to the provincial-terrain data layer.",
            "Added red highlighting and status messages for unassigned provinces.",
            "Added yellow highlighting for batch state creation.",
            "Added railway and supply-hub overlays.",
            "Added live ridge-line feedback.",
            "Improved font, color, and label readability.",
            "Expanded the recent-project list and added tooltips.",
            "Added prominent generation buttons to the height, terrain, and river pages.",
            "Added risk labels to mode navigation.",
            "Redesigned the river page as a three-step workflow.",
            "Made provincial terrain default to inspection mode; assignment must be enabled explicitly.",
            "Removed invalid river-width indices 5 and 8 from the picker.",
        ],
    },
    "1.0.1-beta": {
        "date": "2026-04-15",
        "changes": [
            "Consolidated thirteen modes into seven icon-navigation groups with subtabs.",
            "Unified circular brushes across density, land, terrain, and river tools.",
            "Added local coastline smoothing.",
            "Improved section-title hierarchy.",
            "Made mode hints auto-size and wrap.",
        ],
    },
    "1.0.1": {
        "date": "2026-04-14",
        "changes": [
            "Added smart heightmap generation with coast distance fields and Perlin mountain noise.",
            "Added smart terrain generation with height bands, noisy boundaries, and patches.",
            "Added a circular terrain brush with adjustable soft edges.",
            "Fixed normal-map generation for visible in-game relief.",
            "Fixed export crashes while retaining vanilla decision and raid categories.",
            "Reordered height and terrain modes.",
            "Rewrote the height page with instructions, seeds, and mountain strength controls.",
            "Restored collapsible tool groups and overall panel scrolling.",
        ],
    },
    "1.0.0-beta.1": {
        "date": "2026-04-14",
        "changes": [
            "Reduced export time from more than ten minutes to approximately five seconds.",
            "Fixed coastal provinces without ports so exported MODs can start normally.",
            "Added export preflight with automatic completion of missing data.",
            "Added export-scope selection for map, states, countries, and other content.",
            "Added incremental province generation for a selected area.",
            "Fixed imported MOD-map crashes.",
            "Fixed cities.bmp dimensions.",
            "Fixed coast depressions in generated heightmaps.",
            "Added the HOI4 wiki reference library under docs/wiki/.",
            "Rewrote the project development notes.",
        ],
    },
}
