"""DDS format strategy and encoder-capability handling (M6.5).

Makes the selected profile's DDS format contract explicit and inspectable:
expected FourCC/pixel format, dimensions, mip policy, DX10-header flag, and
whether the bundled writers can generate satisfying bytes at all.

Capability summary: the repository ships deterministic, dependency-free
writers: an uncompressed BGRA8 writer plus a deterministic BC3/DXT5 block
encoder with mip chains (see export/writers/map/colormap_dds.py and the
encoder helpers below). No network dependency is added and no proprietary
tool is required. Assets whose profile contract demands BC3/DXT5 (water
colormaps, fog of war) are generated by the bundled encoder; the planner
preserves validated compatible imported bytes when they satisfy the
contract and records an explicit blocked resolution with an actionable
remedy only for unsupported formats or impossible contracts. Generated
bytes are always honestly labeled and never mislabeled.

Public entry points:

- describe_encoder_capability: what the bundled writers can/can not emit.
- strategy_for_asset: per-path contract strategy for a profile and map size.
- describe_profile_dds: every DDS contract of a profile, sorted by path.
- parse_dds_header: parse a 128-byte (or 148-byte DX10) DDS header.
- is_compatible_dds: check imported bytes against a strategy.
- decide_dds_output: generate / preserve / blocked decision with reasons.
- expected_bc_payload_size: block-compressed payload math for BC1/2/3.
- build_bgra8_header: single source of truth for emitted BGRA8 headers.
- build_dxt5_header: single source of truth for emitted BC3/DXT5 headers.
- encode_bc3_block: deterministic single 4x4 BC3 block encoder.
- encode_bc3_payload: deterministic single-level BC3 payload with edge replication.
- downsample_rgba_box: deterministic area-average downsampler for mip chains.
- generate_bc3_mip_chain: deterministic mip levels plus concatenated payload.
- encode_dxt5_payload: deterministic multi-mip BC3 payload.
- encode_dxt5_dds: deterministic full BC3/DXT5 file bytes (header plus payload).

The module is import-time dependency-free (stdlib only; numpy is imported
lazily inside the encoder helpers) so validators, the planner, writers,
and tests can share one contract without import cycles.
"""
from __future__ import annotations

import struct


STRATEGY_VERSION = "dds-strategy/6.5"

ENCODER_PROVENANCE = (
    "dependency-free uncompressed BGRA8 writer in "
    "export/writers/map/colormap_dds.py; no network access is used, and "
    "no proprietary tool is required"
)

BC3_ENCODER_PROVENANCE = (
    "dependency-free deterministic BC3/DXT5 block encoder in "
    "domain/dds_format.py (numpy only; no network access is used, and no "
    "proprietary tool or external command is required)"
)

GENERATABLE_FORMATS = frozenset({"BGRA8", "DXT5"})

BC3_BLOCK_BYTES = 16
DXT5_FOURCC = b"DXT5"

BLOCK_COMPRESSED_FORMATS = frozenset({"DXT1", "DXT3", "DXT5"})

FOURCC_ALIASES = {"BC1": "DXT1", "BC2": "DXT3", "BC3": "DXT5"}

DDS_MAGIC = b"DDS "
DDS_HEADER_SIZE = 128
DX10_EXTENDED_SIZE = 20

BGRA8_R_MASK = 0x00FF0000
BGRA8_G_MASK = 0x0000FF00
BGRA8_B_MASK = 0x000000FF
BGRA8_A_MASK = 0xFF000000

REMEDY_IMPORT_OR_INHERIT = (
    "import a compatible DDS with matching FourCC, dimensions, and mip "
    "chain so its bytes can be preserved, inherit the file from the "
    "selected game install, or record an accepted exception before freezing"
)


class DdsStrategy:
    """Inspectable per-asset DDS contract strategy.

    Attributes mirror the profile contract (four_cc, dimensions, mip
    policy, DX10 flag) plus the encoder capability verdict
    (can_generate, encoder, provenance) and a human-readable reason.
    """

    __slots__ = (
        "rel_path",
        "expected_width",
        "expected_height",
        "four_cc",
        "mip_count",
        "has_dx10_header",
        "pixel_format",
        "can_generate",
        "encoder",
        "provenance",
        "requirement",
        "reason",
    )

    def __init__(
        self,
        rel_path="",
        expected_width=None,
        expected_height=None,
        four_cc="",
        mip_count=None,
        has_dx10_header=None,
        pixel_format="",
        can_generate=False,
        encoder="",
        provenance="",
        requirement="no-contract",
        reason="",
    ):
        self.rel_path = str(rel_path or "")
        self.expected_width = expected_width
        self.expected_height = expected_height
        self.four_cc = str(four_cc or "")
        self.mip_count = mip_count
        self.has_dx10_header = has_dx10_header
        self.pixel_format = str(pixel_format or "")
        self.can_generate = bool(can_generate)
        self.encoder = str(encoder or "")
        self.provenance = str(provenance or "")
        self.requirement = str(requirement or "no-contract")
        self.reason = str(reason or "")

    def to_dict(self):
        return {
            "rel_path": self.rel_path,
            "expected_width": self.expected_width,
            "expected_height": self.expected_height,
            "four_cc": self.four_cc,
            "mip_count": self.mip_count,
            "has_dx10_header": self.has_dx10_header,
            "pixel_format": self.pixel_format,
            "can_generate": self.can_generate,
            "encoder": self.encoder,
            "provenance": self.provenance,
            "requirement": self.requirement,
            "reason": self.reason,
        }

    def __eq__(self, other):
        if not isinstance(other, DdsStrategy):
            return NotImplemented
        return self.to_dict() == other.to_dict()

    def __repr__(self):
        return (
            "DdsStrategy(%r, four_cc=%r, size=%r, mips=%r, can_generate=%r)"
            % (
                self.rel_path,
                self.four_cc,
                (self.expected_width, self.expected_height),
                self.mip_count,
                self.can_generate,
            )
        )


class DdsDecision:
    """generate / preserve / blocked verdict for one DDS path."""

    __slots__ = ("rel_path", "action", "reason", "remedy", "provenance")

    def __init__(self, rel_path="", action="", reason="", remedy="", provenance=""):
        self.rel_path = str(rel_path or "")
        self.action = str(action or "")
        self.reason = str(reason or "")
        self.remedy = str(remedy or "")
        self.provenance = str(provenance or "")

    def to_dict(self):
        return {
            "rel_path": self.rel_path,
            "action": self.action,
            "reason": self.reason,
            "remedy": self.remedy,
            "provenance": self.provenance,
        }

    def __eq__(self, other):
        if not isinstance(other, DdsDecision):
            return NotImplemented
        return self.to_dict() == other.to_dict()

    def __repr__(self):
        return "DdsDecision(%r, action=%r)" % (self.rel_path, self.action)


def normalize_fourcc(value):
    """Normalize a FourCC/format label to a canonical token.

    BC1/BC2/BC3 are aliases of DXT1/DXT3/DXT5, and combined labels such
    as BC3/DXT5 match on their first part. Returns "" when uninterpretable.
    """
    if value is None:
        return ""
    if isinstance(value, bytes):
        try:
            value = value.split(b"\x00")[0].decode("ascii")
        except (UnicodeDecodeError, ValueError):
            return ""
    try:
        text = str(value).strip().upper()
    except (TypeError, ValueError):
        return ""
    if not text:
        return ""
    first = text.split("/")[0].strip()
    first = first.split()[0] if first.split() else ""
    if not first:
        return ""
    aliased = FOURCC_ALIASES.get(first, first)
    if aliased == "DX10":
        return "DX10"
    if aliased in BLOCK_COMPRESSED_FORMATS or aliased == "BGRA8":
        return aliased
    return first


def describe_encoder_capability():
    """Probe what the bundled writers can emit (no I/O, deterministic).

    Returns a plain dict so manifests and diagnostics can embed it
    without new types. BGRA8 and BC3/DXT5 (with mip chains) are supported
    by the bundled dependency-free encoders; other block formats remain
    unsupported and keep honest blocked resolutions.
    """
    return {
        "schema": STRATEGY_VERSION,
        "bgra8_uncompressed": "supported",
        "bc1_dxt1": "unsupported",
        "bc2_dxt3": "unsupported",
        "bc3_dxt5": "supported",
        "mip_chain_writes": "bgra8 single-mip plus deterministic BC3/DXT5 mip chains",
        "deterministic": True,
        "network_required": False,
        "external_tools_required": (),
        "provenance": ENCODER_PROVENANCE + "; " + BC3_ENCODER_PROVENANCE,
    }


def _contract_field(contract, names):
    for name in names:
        try:
            if hasattr(contract, name):
                return getattr(contract, name)
        except (AttributeError, TypeError, ValueError):
            pass
        try:
            if isinstance(contract, dict) and name in contract:
                return contract[name]
        except (TypeError, ValueError):
            pass
    return None


def _as_int(value):
    try:
        if isinstance(value, bool):
            return None
        return int(value)
    except (TypeError, ValueError):
        return None


def _as_bool(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    try:
        text = str(value).strip().lower()
    except (TypeError, ValueError):
        return None
    if text in ("1", "true", "yes", "y", "on"):
        return True
    if text in ("0", "false", "no", "n", "off", ""):
        return False if text else None
    return None


def has_contract(profile, rel_path):
    """Return True when the profile declares a DDS contract for rel_path."""
    try:
        dds_map = getattr(profile, "dds", None)
    except (AttributeError, TypeError, ValueError):
        return False
    try:
        norm = str(rel_path or "").replace("\\", "/")
    except (TypeError, ValueError):
        return False
    try:
        if isinstance(dds_map, dict):
            return norm in dds_map
    except (TypeError, ValueError):
        pass
    return False


def strategy_for_asset(rel_path, profile=None, map_width=None, map_height=None):
    """Build the inspectable DDS strategy for one asset path.

    Dimensions come from the profile contract when map dimensions are
    known; unknown dimensions leave expected_width/height as None and
    skip dimension checks downstream. Paths without a profile contract
    keep the legacy generatable behavior with requirement no-contract.
    """
    norm = str(rel_path or "").replace("\\", "/")
    contract = None
    if profile is not None:
        try:
            dds_map = getattr(profile, "dds", None)
            if isinstance(dds_map, dict):
                contract = dds_map.get(norm)
        except (AttributeError, TypeError, ValueError):
            contract = None
    if contract is None:
        return DdsStrategy(
            rel_path=norm,
            four_cc="",
            pixel_format="UNKNOWN",
            can_generate=True,
            encoder="bgra8-legacy",
            provenance=ENCODER_PROVENANCE,
            requirement="no-contract",
            reason=(
                "no profile DDS contract for %r; legacy BGRA8 generation "
                "applies" % norm
            ),
        )
    four_cc = normalize_fourcc(
        _contract_field(contract, ("four_cc", "fourcc", "format", "pixel_format"))
    )
    mip_count = _as_int(
        _contract_field(
            contract,
            ("mip_count", "mips", "mipmaps", "mip_levels", "mipmap_count"),
        )
    )
    has_dx10 = _as_bool(
        _contract_field(contract, ("has_dx10_header", "dx10", "dx10_header"))
    )
    width = None
    height = None
    try:
        map_w = int(map_width)
        map_h = int(map_height)
    except (TypeError, ValueError):
        map_w = None
        map_h = None
    if map_w is not None and map_h is not None and profile is not None:
        try:
            size = profile.expected_dds_size(norm, map_w, map_h)
        except (AttributeError, TypeError, ValueError):
            size = None
        if size is not None:
            try:
                width = int(size[0])
                height = int(size[1])
            except (TypeError, ValueError, IndexError):
                width = None
                height = None
    pixel_format = four_cc or "UNKNOWN"
    can_generate = four_cc in GENERATABLE_FORMATS
    if can_generate:
        if four_cc == "DXT5":
            reason = (
                "profile contract for %r is %s and the bundled "
                "deterministic BC3/DXT5 encoder satisfies it" % (norm, four_cc)
            )
            encoder = "bc3-dxt5"
            provenance = BC3_ENCODER_PROVENANCE
        else:
            reason = (
                "profile contract for %r is %s and the bundled BGRA8 writer "
                "satisfies it" % (norm, four_cc)
            )
            encoder = "bgra8"
            provenance = ENCODER_PROVENANCE
    else:
        reason = (
            "profile contract for %r requires %s but no bundled encoder "
            "can emit it; generation cannot satisfy it"
            % (norm, four_cc or "an unknown format")
        )
        encoder = "unavailable-encoder"
        provenance = ENCODER_PROVENANCE
    return DdsStrategy(
        rel_path=norm,
        expected_width=width,
        expected_height=height,
        four_cc=four_cc,
        mip_count=mip_count,
        has_dx10_header=has_dx10,
        pixel_format=pixel_format,
        can_generate=can_generate,
        encoder=encoder,
        provenance=provenance,
        requirement="profile-contract",
        reason=reason,
    )


def describe_profile_dds(profile, map_width=None, map_height=None):
    """Return sorted DdsStrategy entries for every DDS contract of profile."""
    try:
        dds_map = getattr(profile, "dds", None)
    except (AttributeError, TypeError, ValueError):
        return []
    if not isinstance(dds_map, dict):
        return []
    try:
        paths = sorted(dds_map)
    except TypeError:
        return []
    strategies = []
    for path in paths:
        try:
            strategies.append(
                strategy_for_asset(path, profile, map_width, map_height)
            )
        except (AttributeError, TypeError, ValueError):
            continue
    return strategies


def build_bgra8_header(width, height):
    """Build the 128-byte uncompressed BGRA8 DDS header we emit.

    Single source of truth for emitted headers: flags 0x100f, pitch of
    width*4, pixel-format flags ALPHAPIXELS|RGB, 32-bit BGRA masks, and a
    single mip level. Matches the installed vanilla main-colormap shape.
    """
    width = int(width)
    height = int(height)
    header = bytearray(DDS_HEADER_SIZE)
    header[0:4] = DDS_MAGIC
    struct.pack_into("<I", header, 4, 124)
    struct.pack_into("<I", header, 8, 0x100F)
    struct.pack_into("<I", header, 12, height)
    struct.pack_into("<I", header, 16, width)
    struct.pack_into("<I", header, 20, width * 4)
    struct.pack_into("<I", header, 24, 0)
    struct.pack_into("<I", header, 28, 1)
    struct.pack_into("<I", header, 76, 32)
    struct.pack_into("<I", header, 80, 0x41)
    struct.pack_into("<I", header, 84, 0)
    struct.pack_into("<I", header, 88, 32)
    struct.pack_into("<I", header, 92, BGRA8_R_MASK)
    struct.pack_into("<I", header, 96, BGRA8_G_MASK)
    struct.pack_into("<I", header, 100, BGRA8_B_MASK)
    struct.pack_into("<I", header, 104, BGRA8_A_MASK)
    struct.pack_into("<I", header, 108, 0x1000)
    return bytes(header)


def parse_dds_header(data):
    """Parse a DDS header into inspectable fields.

    Accepts bytes-like input holding at least the 128-byte header (148
    bytes for DX10-extended files). Returns a dict with width, height,
    four_cc (normalized), mip_count, has_dx10_header, header_size,
    payload_size, and pixel_format. Raises ValueError on malformed input.
    """
    try:
        raw = bytes(data)
    except (TypeError, ValueError) as exc:
        raise ValueError("DDS data must be bytes-like: %s" % exc)
    if len(raw) < DDS_HEADER_SIZE:
        raise ValueError(
            "DDS data is %d bytes; need at least %d for a header"
            % (len(raw), DDS_HEADER_SIZE)
        )
    if raw[0:4] != DDS_MAGIC:
        raise ValueError("DDS magic is %r; expected bDDS " % raw[0:4])
    (size,) = struct.unpack_from("<I", raw, 4)
    if size != 124:
        raise ValueError("DDS dwSize is %d; expected 124" % size)
    (height,) = struct.unpack_from("<I", raw, 12)
    (width,) = struct.unpack_from("<I", raw, 16)
    (mip_count,) = struct.unpack_from("<I", raw, 28)
    if not mip_count:
        mip_count = 1
    (pf_size,) = struct.unpack_from("<I", raw, 76)
    if pf_size != 32:
        raise ValueError("DDS pixel-format size is %d; expected 32" % pf_size)
    fourcc_raw = raw[84:88]
    if fourcc_raw == b"DX10":
        if len(raw) < DDS_HEADER_SIZE + DX10_EXTENDED_SIZE:
            raise ValueError("DDS DX10 extended header is truncated")
        return {
            "width": int(width),
            "height": int(height),
            "four_cc": "DX10",
            "mip_count": int(mip_count),
            "has_dx10_header": True,
            "header_size": DDS_HEADER_SIZE + DX10_EXTENDED_SIZE,
            "payload_size": len(raw) - DDS_HEADER_SIZE - DX10_EXTENDED_SIZE,
            "pixel_format": "DX10",
        }
    try:
        label = fourcc_raw.split(b"\x00")[0].decode("ascii").strip().upper()
    except (UnicodeDecodeError, ValueError):
        label = ""
    if label:
        four_cc = normalize_fourcc(label)
        pixel_format = four_cc
    else:
        try:
            (rgb_bits,) = struct.unpack_from("<I", raw, 88)
            (r_mask,) = struct.unpack_from("<I", raw, 92)
            (g_mask,) = struct.unpack_from("<I", raw, 96)
            (b_mask,) = struct.unpack_from("<I", raw, 100)
            (a_mask,) = struct.unpack_from("<I", raw, 104)
        except struct.error as exc:
            raise ValueError("DDS pixel-format fields are truncated: %s" % exc)
        if (
            rgb_bits == 32
            and r_mask == BGRA8_R_MASK
            and g_mask == BGRA8_G_MASK
            and b_mask == BGRA8_B_MASK
            and a_mask == BGRA8_A_MASK
        ):
            four_cc = "BGRA8"
            pixel_format = "BGRA8"
        else:
            four_cc = "UNCOMPRESSED"
            pixel_format = "UNCOMPRESSED-%d" % rgb_bits
    return {
        "width": int(width),
        "height": int(height),
        "four_cc": four_cc,
        "mip_count": int(mip_count),
        "has_dx10_header": False,
        "header_size": DDS_HEADER_SIZE,
        "payload_size": len(raw) - DDS_HEADER_SIZE,
        "pixel_format": pixel_format,
    }


def expected_bc_payload_size(width, height, four_cc, mip_count=1):
    """Derive the block-compressed payload size for BC1/2/3 assets.

    DXT1 uses 8 bytes per 4x4 block; DXT3/DXT5 use 16. Mip levels halve
    each dimension (floored at 1). Returns None for formats without
    block math or uninterpretable inputs.
    """
    token = normalize_fourcc(four_cc)
    if token == "DXT1":
        per_block = 8
    elif token in ("DXT3", "DXT5"):
        per_block = 16
    else:
        return None
    try:
        width = int(width)
        height = int(height)
        mips = int(mip_count) if mip_count is not None else 1
    except (TypeError, ValueError):
        return None
    if width <= 0 or height <= 0 or mips <= 0:
        return None
    total = 0
    level_w = width
    level_h = height
    for _ in range(mips):
        blocks_w = max(1, (level_w + 3) // 4)
        blocks_h = max(1, (level_h + 3) // 4)
        total += blocks_w * blocks_h * per_block
        level_w = max(1, level_w // 2)
        level_h = max(1, level_h // 2)
    return total


def is_compatible_dds(data, strategy):
    """Check imported DDS bytes against a strategy.

    Returns (True, reason) when the bytes satisfy every contract field
    the strategy specifies, else (False, reason naming the first
    mismatch). Unknown strategy fields are skipped, never invented.
    """
    try:
        info = parse_dds_header(data)
    except ValueError as exc:
        return (False, "imported bytes are not a parseable DDS: %s" % exc)
    if strategy is None:
        return (True, "no strategy constrains the imported bytes")
    if (
        strategy.expected_width is not None
        and info["width"] != strategy.expected_width
    ) or (
        strategy.expected_height is not None
        and info["height"] != strategy.expected_height
    ):
        return (
            False,
            "imported DDS is %dx%d; contract expects %sx%s"
            % (
                info["width"],
                info["height"],
                strategy.expected_width,
                strategy.expected_height,
            ),
        )
    if strategy.four_cc and info["four_cc"] != strategy.four_cc:
        if strategy.four_cc == "DX10" or info["four_cc"] == "DX10":
            return (
                False,
                "imported DDS DX10 header flag disagrees with the contract",
            )
        return (
            False,
            "imported DDS format is %s; contract expects %s"
            % (info["four_cc"], strategy.four_cc),
        )
    if (
        strategy.mip_count is not None
        and info["mip_count"] != strategy.mip_count
    ):
        return (
            False,
            "imported DDS has %d mips; contract expects %d"
            % (info["mip_count"], strategy.mip_count),
        )
    if (
        strategy.has_dx10_header is not None
        and info["has_dx10_header"] != strategy.has_dx10_header
    ):
        return (
            False,
            "imported DDS has_dx10_header is %s; contract expects %s"
            % (info["has_dx10_header"], strategy.has_dx10_header),
        )
    if strategy.four_cc in BLOCK_COMPRESSED_FORMATS:
        expected = expected_bc_payload_size(
            info["width"], info["height"], info["four_cc"], info["mip_count"]
        )
        if expected is not None and info["payload_size"] != expected:
            return (
                False,
                "imported DDS payload is %d bytes; %s payload expects %d"
                % (info["payload_size"], info["four_cc"], expected),
            )
    return (
        True,
        "imported DDS satisfies the %s contract (%dx%d, %s, %d mips)"
        % (
            strategy.four_cc or "legacy",
            info["width"],
            info["height"],
            info["four_cc"],
            info["mip_count"],
        ),
    )


def _has_usable_bytes(value):
    try:
        return isinstance(value, (bytes, bytearray, memoryview)) and len(value) > 0
    except (TypeError, ValueError):
        return False


def _encoder_label_for(four_cc):
    token = normalize_fourcc(four_cc) or "BGRA8"
    if token == "DXT5":
        return "the bundled deterministic BC3/DXT5 encoder"
    return "the bundled BGRA8 writer"


def decide_dds_output(strategy, imported_bytes=None, dirty=False):
    """Decide generate / preserve / blocked for one DDS path.

    Generatable (BGRA8 and BC3/DXT5) contracts regenerate whenever imports
    are missing, dirty, or incompatible, and preserve validated compatible
    imports. Non-generatable contracts preserve only validated compatible
    clean imports; every other case is blocked with an actionable remedy
    instead of emitting mislabeled bytes.
    """
    rel_path = getattr(strategy, "rel_path", "")
    dirty = bool(dirty)
    usable = _has_usable_bytes(imported_bytes)
    if strategy is not None and strategy.can_generate:
        four_cc = strategy.four_cc or "BGRA8"
        encoder_label = _encoder_label_for(four_cc)
        if dirty:
            return DdsDecision(
                rel_path,
                "generate",
                "asset is dirty; %s regenerates it "
                "and satisfies the %s contract" % (encoder_label, four_cc),
                "",
                "writer-generated",
            )
        if usable:
            ok, why = is_compatible_dds(imported_bytes, strategy)
            if ok:
                return DdsDecision(
                    rel_path,
                    "preserve",
                    "clean compatible imported bytes are written back; %s" % why,
                    "",
                    "project-assets",
                )
            return DdsDecision(
                rel_path,
                "generate",
                "clean imported bytes are incompatible (%s); %s regenerates "
                "satisfying bytes" % (why, encoder_label),
                "",
                "writer-generated",
            )
        return DdsDecision(
            rel_path,
            "generate",
            "no imported bytes; %s generates output "
            "satisfying the %s contract" % (encoder_label, four_cc),
            "",
            "writer-generated",
        )
    expected = getattr(strategy, "four_cc", "") if strategy is not None else ""
    expected = expected or "the profile format"
    if usable and not dirty:
        ok, why = is_compatible_dds(imported_bytes, strategy)
        if ok:
            return DdsDecision(
                rel_path,
                "preserve",
                "clean compatible imported bytes are written back "
                "unrecompressed; %s" % why,
                "",
                "project-assets",
            )
        return DdsDecision(
            rel_path,
            "blocked",
            "clean imported bytes are incompatible (%s) and the profile "
            "requires %s, which no bundled encoder can emit" % (why, expected),
            REMEDY_IMPORT_OR_INHERIT,
            "dds-capability",
        )
    if dirty:
        return DdsDecision(
            rel_path,
            "blocked",
            "asset is dirty and requires regeneration, but the profile "
            "requires %s, which no bundled encoder can emit" % expected,
            REMEDY_IMPORT_OR_INHERIT,
            "dds-capability",
        )
    return DdsDecision(
        rel_path,
        "blocked",
        "no compatible imported bytes exist and the profile requires %s, "
        "which no bundled encoder can emit; on-disk preview bytes would "
        "not satisfy the contract" % expected,
        REMEDY_IMPORT_OR_INHERIT,
        "dds-capability",
    )

# ---------------------------------------------------------------------------
# Deterministic dependency-free BC3/DXT5 block encoder with mip chains (M6.5).
#
# Numpy is imported lazily so this module stays import-time stdlib-only.
# Integer arithmetic only, no randomness, no network, no external tools:
# identical inputs always produce identical bytes on any platform.
# ---------------------------------------------------------------------------


def _require_numpy():
    try:
        import numpy as np
    except ImportError as exc:
        raise ImportError(
            "the BC3/DXT5 encoder needs numpy, which the exporter already "
            "requires: %s" % exc
        )
    return np


def _normalize_rgba(pixels, order="RGBA"):
    """Normalize HxWx3/HxWx4 input to a contiguous HxWx4 RGBA uint8 array."""
    np = _require_numpy()
    try:
        label = str(order or "RGBA").strip().upper()
    except (TypeError, ValueError) as exc:
        raise ValueError("pixel order is unusable: %s" % exc)
    if label not in ("RGBA", "BGRA"):
        raise ValueError(
            "pixel order %r is unknown; expected RGBA or BGRA" % (order,)
        )
    try:
        arr = np.ascontiguousarray(pixels)
    except (TypeError, ValueError) as exc:
        raise ValueError("raster input cannot be read as an array: %s" % exc)
    if arr.ndim != 3 or arr.shape[2] not in (3, 4):
        raise ValueError(
            "raster input must be HxWx3 or HxWx4, got shape %r"
            % (getattr(arr, "shape", None),)
        )
    try:
        height = int(arr.shape[0])
        width = int(arr.shape[1])
    except (TypeError, ValueError) as exc:
        raise ValueError("raster dimensions are unusable: %s" % exc)
    if height <= 0 or width <= 0:
        raise ValueError("raster dimensions must be positive")
    if arr.dtype != np.uint8:
        try:
            arr = np.clip(arr, 0, 255).astype(np.uint8)
        except (TypeError, ValueError) as exc:
            raise ValueError("raster input must be uint8-compatible: %s" % exc)
    else:
        arr = np.ascontiguousarray(arr)
    channels = int(arr.shape[2])
    if channels == 3:
        if label == "BGRA":
            rgb = np.ascontiguousarray(arr[:, :, [2, 1, 0]])
        else:
            rgb = np.ascontiguousarray(arr)
        alpha = np.full((height, width, 1), 255, dtype=np.uint8)
        return np.ascontiguousarray(np.concatenate([rgb, alpha], axis=2))
    if label == "BGRA":
        return np.ascontiguousarray(arr[:, :, [2, 1, 0, 3]])
    return np.ascontiguousarray(arr)


def _pad_to_blocks(rgba):
    np = _require_numpy()
    height = int(rgba.shape[0])
    width = int(rgba.shape[1])
    pad_h = (-height) % 4
    pad_w = (-width) % 4
    if pad_h == 0 and pad_w == 0:
        return np.ascontiguousarray(rgba)
    return np.ascontiguousarray(
        np.pad(rgba, ((0, pad_h), (0, pad_w), (0, 0)), mode="edge")
    )


def _blocks_view(padded):
    np = _require_numpy()
    padded_h = int(padded.shape[0])
    padded_w = int(padded.shape[1])
    blocks_h = padded_h // 4
    blocks_w = padded_w // 4
    count = blocks_h * blocks_w
    view = padded.reshape(blocks_h, 4, blocks_w, 4, 4)
    view = view.transpose(0, 2, 1, 3, 4).reshape(count, 4, 4, 4)
    return (view, blocks_h, blocks_w)


def _encode_blocks_to_bytes(alpha_idx, alpha_lo, alpha_hi, color_idx, c0, c1):
    np = _require_numpy()
    count = int(alpha_idx.shape[0])
    alpha_idx = np.ascontiguousarray(alpha_idx, dtype=np.uint64)
    color_idx = np.ascontiguousarray(color_idx, dtype=np.uint32)
    shifts_a = (np.arange(16, dtype=np.uint64) * np.uint64(3))
    alpha_bits = np.sum(alpha_idx * (np.uint64(1) << shifts_a), axis=1).astype(np.uint64)
    shifts_c = (np.arange(16, dtype=np.uint32) * np.uint32(2))
    color_bits = np.sum(color_idx * (np.uint32(1) << shifts_c), axis=1).astype(np.uint32)
    le64 = alpha_bits.astype("<u8").tobytes()
    tail6 = np.frombuffer(le64, dtype=np.uint8).reshape(count, 8)[:, :6]
    alpha_arr = np.empty((count, 8), dtype=np.uint8)
    alpha_arr[:, 0] = np.ascontiguousarray(alpha_lo, dtype=np.uint8)
    alpha_arr[:, 1] = np.ascontiguousarray(alpha_hi, dtype=np.uint8)
    alpha_arr[:, 2:8] = tail6
    le32 = color_bits.astype("<u4").tobytes()
    color_tail = np.frombuffer(le32, dtype=np.uint8).reshape(count, 4)
    c0le = np.ascontiguousarray(c0, dtype="<u2").tobytes()
    c1le = np.ascontiguousarray(c1, dtype="<u2").tobytes()
    c0b = np.frombuffer(c0le, dtype=np.uint8).reshape(count, 2)
    c1b = np.frombuffer(c1le, dtype=np.uint8).reshape(count, 2)
    color_arr = np.empty((count, 8), dtype=np.uint8)
    color_arr[:, 0:2] = c0b
    color_arr[:, 2:4] = c1b
    color_arr[:, 4:8] = color_tail
    out = np.empty((count, 16), dtype=np.uint8)
    out[:, 0:8] = alpha_arr
    out[:, 8:16] = color_arr
    return bytes(out.tobytes())


def _encode_rgba_array_bc3(rgba):
    np = _require_numpy()
    rgba = np.ascontiguousarray(rgba, dtype=np.uint8)
    padded = _pad_to_blocks(rgba)
    view, _bh, _bw = _blocks_view(padded)
    count = int(view.shape[0])
    texels_a = view[:, :, :, 3].reshape(count, 16).astype(np.int32)
    texels_rgb = view[:, :, :, :3].reshape(count, 16, 3).astype(np.int32)
    a0 = texels_a.max(axis=1).astype(np.int32)
    a1 = texels_a.min(axis=1).astype(np.int32)
    pal_a = np.empty((count, 8), dtype=np.int32)
    pal_a[:, 0] = a0
    pal_a[:, 1] = a1
    pal_a[:, 2] = (6 * a0 + 1 * a1) // 7
    pal_a[:, 3] = (5 * a0 + 2 * a1) // 7
    pal_a[:, 4] = (4 * a0 + 3 * a1) // 7
    pal_a[:, 5] = (3 * a0 + 4 * a1) // 7
    pal_a[:, 6] = (2 * a0 + 5 * a1) // 7
    pal_a[:, 7] = (1 * a0 + 6 * a1) // 7
    diff_a = np.abs(texels_a[:, :, None] - pal_a[:, None, :])
    alpha_idx = np.argmin(diff_a, axis=2).astype(np.uint64)
    sums = texels_rgb.sum(axis=2)
    pick_max = np.argmax(sums, axis=1)
    pick_min = np.argmin(sums, axis=1)
    rows = np.arange(count)
    cmax = texels_rgb[rows, pick_max].astype(np.int32)
    cmin = texels_rgb[rows, pick_min].astype(np.int32)
    vmax = ((cmax[:, 0] >> 3) << 11) | ((cmax[:, 1] >> 2) << 5) | (cmax[:, 2] >> 3)
    vmin = ((cmin[:, 0] >> 3) << 11) | ((cmin[:, 1] >> 2) << 5) | (cmin[:, 2] >> 3)
    c0 = np.maximum(vmax, vmin).astype(np.uint16)
    c1 = np.minimum(vmax, vmin).astype(np.uint16)
    r0 = ((c0 >> 11) & 31).astype(np.int32)
    g0 = ((c0 >> 5) & 63).astype(np.int32)
    b0 = (c0 & 31).astype(np.int32)
    r1 = ((c1 >> 11) & 31).astype(np.int32)
    g1 = ((c1 >> 5) & 63).astype(np.int32)
    b1 = (c1 & 31).astype(np.int32)
    r0e = (r0 << 3) | (r0 >> 2)
    g0e = (g0 << 2) | (g0 >> 4)
    b0e = (b0 << 3) | (b0 >> 2)
    r1e = (r1 << 3) | (r1 >> 2)
    g1e = (g1 << 2) | (g1 >> 4)
    b1e = (b1 << 3) | (b1 >> 2)
    pal_c = np.empty((count, 4, 3), dtype=np.int32)
    pal_c[:, 0, 0] = r0e
    pal_c[:, 0, 1] = g0e
    pal_c[:, 0, 2] = b0e
    pal_c[:, 1, 0] = r1e
    pal_c[:, 1, 1] = g1e
    pal_c[:, 1, 2] = b1e
    pal_c[:, 2, 0] = (2 * r0e + r1e) // 3
    pal_c[:, 2, 1] = (2 * g0e + g1e) // 3
    pal_c[:, 2, 2] = (2 * b0e + b1e) // 3
    pal_c[:, 3, 0] = (r0e + 2 * r1e) // 3
    pal_c[:, 3, 1] = (g0e + 2 * g1e) // 3
    pal_c[:, 3, 2] = (b0e + 2 * b1e) // 3
    delta = texels_rgb[:, :, None, :] - pal_c[:, None, :, :]
    dist = np.sum(delta * delta, axis=3)
    color_idx = np.argmin(dist, axis=2).astype(np.uint32)
    return _encode_blocks_to_bytes(
        alpha_idx, a0.astype(np.uint8), a1.astype(np.uint8),
        color_idx, c0, c1,
    )


def encode_bc3_block(rgba_block, order="RGBA"):
    """Encode one 4x4 RGBA/BGRA block to 16 deterministic BC3 bytes."""
    rgba = _normalize_rgba(rgba_block, order=order)
    if int(rgba.shape[0]) != 4 or int(rgba.shape[1]) != 4:
        raise ValueError(
            "encode_bc3_block needs a 4x4 raster, got shape %r"
            % (rgba.shape,)
        )
    return _encode_rgba_array_bc3(rgba)


def encode_bc3_payload(pixels, order="RGBA"):
    """Encode one mip level to BC3 bytes with edge replication.

    Non-multiple-of-4 dimensions replicate the edge texels so every level
    always yields exactly expected_bc_payload_size(width, height, DXT5, 1)
    bytes. Deterministic integer arithmetic only.
    """
    rgba = _normalize_rgba(pixels, order=order)
    return _encode_rgba_array_bc3(rgba)


def downsample_rgba_box(base, new_width, new_height):
    """Deterministic area-average downsample to new_width by new_height.

    Each destination texel averages the source rectangle that maps onto
    it with integer rounding, so halving even dimensions equals an exact
    2x2 box average and odd dimensions degrade gracefully. Identical
    inputs always produce identical outputs.
    """
    np = _require_numpy()
    rgba = _normalize_rgba(base, order="RGBA")
    try:
        new_width = int(new_width)
        new_height = int(new_height)
    except (TypeError, ValueError) as exc:
        raise ValueError("downsample dimensions must be integers: %s" % exc)
    if new_width <= 0 or new_height <= 0:
        raise ValueError("downsample dimensions must be positive")
    src_h = int(rgba.shape[0])
    src_w = int(rgba.shape[1])
    if src_w == new_width and src_h == new_height:
        return np.ascontiguousarray(rgba)
    if src_w == new_width * 2 and src_h == new_height * 2:
        # The map contracts use power-of-two halving for every mip level.
        # Keep that hot path vectorized so a full-map FOW chain does not
        # spend minutes in Python-level per-pixel loops.
        grouped = rgba.reshape(new_height, 2, new_width, 2, 4).astype(np.int32)
        averaged = grouped.sum(axis=(1, 3), dtype=np.int64)
        return np.ascontiguousarray(((averaged + 2) // 4).astype(np.uint8))
    out = np.empty((new_height, new_width, 4), dtype=np.uint8)
    for dst_y in range(new_height):
        y0 = (dst_y * src_h) // new_height
        y1 = ((dst_y + 1) * src_h) // new_height
        if y1 <= y0:
            y1 = y0 + 1
        if y0 >= src_h:
            y0 = src_h - 1
        if y1 > src_h:
            y1 = src_h
        for dst_x in range(new_width):
            x0 = (dst_x * src_w) // new_width
            x1 = ((dst_x + 1) * src_w) // new_width
            if x1 <= x0:
                x1 = x0 + 1
            if x0 >= src_w:
                x0 = src_w - 1
            if x1 > src_w:
                x1 = src_w
            region = rgba[y0:y1, x0:x1, :].astype(np.int32)
            total = region.sum(axis=(0, 1), dtype=np.int64)
            count = max(1, int(region.shape[0]) * int(region.shape[1]))
            out[dst_y, dst_x, :] = ((total + count // 2) // count).astype(np.uint8)
    return np.ascontiguousarray(out)


def mip_level_size(width, height, level):
    """Dimensions of one mip level with halving floored at 1 by 1."""
    try:
        width = int(width)
        height = int(height)
        level = int(level)
    except (TypeError, ValueError) as exc:
        raise ValueError("mip level inputs must be integers: %s" % exc)
    if width <= 0 or height <= 0 or level < 0:
        raise ValueError("mip level inputs must be positive")
    level_w = width
    level_h = height
    for _ in range(level):
        level_w = max(1, level_w // 2)
        level_h = max(1, level_h // 2)
    return (level_w, level_h)


def generate_bc3_mip_chain(base, mip_count=1, order="RGBA"):
    """Generate deterministic mip levels plus the concatenated BC3 payload.

    Returns (levels, payload) where levels is a list of (width, height)
    tuples and payload holds every level back to back. Level zero is the
    input size; each later level halves each dimension floored at 1, so
    over-requested chains repeat the 1x1 level exactly like
    expected_bc_payload_size predicts.
    """
    np = _require_numpy()
    rgba = _normalize_rgba(base, order=order)
    try:
        mip_count = int(mip_count)
    except (TypeError, ValueError) as exc:
        raise ValueError("mip count must be an integer: %s" % exc)
    if mip_count <= 0:
        raise ValueError("mip count must be positive")
    width = int(rgba.shape[1])
    height = int(rgba.shape[0])
    levels = []
    current = rgba
    parts = []
    for level in range(mip_count):
        level_w, level_h = mip_level_size(width, height, level)
        levels.append((level_w, level_h))
        if level > 0:
            current = downsample_rgba_box(current, level_w, level_h)
            current = np.ascontiguousarray(current)
        parts.append(_encode_rgba_array_bc3(current))
    return (levels, b"".join(parts))


def encode_dxt5_payload(pixels, mip_count=1, order="RGBA"):
    """Encode RGBA/BGRA input to a deterministic multi-mip BC3 payload."""
    _levels, payload = generate_bc3_mip_chain(pixels, mip_count=mip_count, order=order)
    return payload


def build_dxt5_header(width, height, mip_count=1):
    """Build the 128-byte BC3/DXT5 DDS header we emit.

    Single source of truth for compressed headers: FourCC DXT5, linear
    size of the top level, mip count field, and texture/mipmap caps. The
    payload that follows must be exactly
    expected_bc_payload_size(width, height, DXT5, mip_count) bytes.
    """
    try:
        width = int(width)
        height = int(height)
        mip_count = int(mip_count)
    except (TypeError, ValueError) as exc:
        raise ValueError("DDS dimensions and mip count must be integers: %s" % exc)
    if width <= 0 or height <= 0 or mip_count <= 0:
        raise ValueError("DDS dimensions and mip count must be positive")
    top_size = expected_bc_payload_size(width, height, "DXT5", 1)
    if top_size is None:
        raise ValueError("cannot derive a DXT5 top-level size")
    if mip_count > 1:
        flags = 0xA1007
        caps1 = 0x401008
    else:
        flags = 0x81007
        caps1 = 0x1000
    header = bytearray(DDS_HEADER_SIZE)
    header[0:4] = DDS_MAGIC
    struct.pack_into("<I", header, 4, 124)
    struct.pack_into("<I", header, 8, flags)
    struct.pack_into("<I", header, 12, height)
    struct.pack_into("<I", header, 16, width)
    struct.pack_into("<I", header, 20, top_size)
    struct.pack_into("<I", header, 24, 0)
    struct.pack_into("<I", header, 28, mip_count)
    struct.pack_into("<I", header, 76, 32)
    struct.pack_into("<I", header, 80, 0x4)
    header[84:88] = DXT5_FOURCC
    struct.pack_into("<I", header, 108, caps1)
    return bytes(header)


def encode_dxt5_dds(pixels, mip_count=1, order="RGBA"):
    """Encode RGBA/BGRA input to full deterministic DXT5 file bytes."""
    rgba = _normalize_rgba(pixels, order=order)
    try:
        mip_count = int(mip_count)
    except (TypeError, ValueError) as exc:
        raise ValueError("mip count must be an integer: %s" % exc)
    if mip_count <= 0:
        raise ValueError("mip count must be positive")
    width = int(rgba.shape[1])
    height = int(rgba.shape[0])
    _levels, payload = generate_bc3_mip_chain(rgba, mip_count=mip_count, order="RGBA")
    expected = expected_bc_payload_size(width, height, "DXT5", mip_count)
    if expected is None or len(payload) != expected:
        raise ValueError(
            "encoder produced %d payload bytes; expected %r" % (len(payload), expected)
        )
    return build_dxt5_header(width, height, mip_count) + payload
