"""M10 regression checks for the isolated acceptance profile contract."""
from __future__ import annotations

import pytest

from domain.managers.state import StateManager
from export.stages.acceptance_content import run
from export.stages.base import StageContext
from export.stages.pipeline import stages_for_profile


pytestmark = pytest.mark.unit


def test_acceptance_content_uses_game_1193_syntax_and_records_compatibility_shadows(
    tmp_path,
):
    states = StateManager()
    first = states.create_state("First")
    first.provinces = [1]
    first.owner_tag = "BEL"
    second = states.create_state("Second")
    second.provinces = [2]
    second.owner_tag = "FRA"
    third = states.create_state("Third")
    third.provinces = [3]
    third.owner_tag = "GER"

    context = StageContext(
        profile_name="acceptance",
        output_dir=str(tmp_path),
        state_mgr=states,
        acceptance_tags=("QAA", "QAB"),
        scratch={"states": {1: [1], 2: [2], 3: [3]}},
    )

    result = run(context)

    assert result.stage == "acceptance_content"
    assert "acceptance_content" in stages_for_profile("acceptance")
    assert (tmp_path / "common/country_tags/99_acceptance_tags.txt").is_file()
    tags = (tmp_path / "common/country_tags/99_acceptance_tags.txt").read_text(
        encoding="utf-8"
    )
    assert 'QAA = "countries/QAA.txt"' in tags
    assert 'QAB = "countries/QAB.txt"' in tags
    for tag in ("QAA", "QAB"):
        assert (tmp_path / f"common/countries/{tag}.txt").is_file()
        assert (tmp_path / f"history/countries/{tag}.txt").is_file()

    def expected_name_pool(tag: str) -> str:
        return (
            f"{tag} = {{\n"
            "\tmale = {\n"
            '\t\tnames = { "John" "Bob" "Lucas" "Marcus" "Alexander" "Alex" "Peter" "Jonas" "Jim" "Johannes" }\n'
            "\t\tsurnames = { }\n"
            "\t\tcallsigns = { }\n"
            "\t}\n"
            "\tfemale = {\n"
            '\t\tnames = { "Juliette" "Anna" "Jessica" "Emma" "Hanna" "Sofia" "Marie" "Hildegard" }\n'
            "\t\tsurnames = { }\n"
            "\t\tcallsigns = { }\n"
            "\t}\n"
            '\tsurnames = { "Smith" "Jones" "Taylor" "Brown" "Williams" "Wilson" "Evans" "Walker" "White" "Roberts" }\n'
            '\tcallsigns = { "Easy Kill" "The Lightning" "The Devil" "Grasshopper" "Handsome" "Moose" "Mouse" "Pebbles" "Sunshine" "Demon" }\n'
            "\tprefix = o_operation\n"
            "\toperation = {\n"
            "\t\t0 = { o_default_operation }\n"
            "\t}\n"
            "\tuse_geographical_default_operation_names = yes\n"
            "\toffensive_operation_suffix = o_strat_offensive_default\n"
            "\tdefensive_operation_suffix = o_strat_defensive_default\n"
            "\tnaval_operation_suffix = o_strat_naval_default\n"
            "}\n"
        )

    names = (tmp_path / "common/names/99_acceptance_names.txt").read_text(
        encoding="utf-8"
    )
    assert names == (
        "# acceptance-only character and operation name pools generated by the acceptance profile\n"
        + expected_name_pool("QAA")
        + "\n"
        + expected_name_pool("QAB")
    )

    expected_country = (
        "# acceptance-only test content generated by the acceptance profile\n"
        "capital = 1\n"
        'oob = "QAA_1936"\n'
        "set_research_slots = 3\n"
        "load_focus_tree = generic_focus\n"
        "set_technology = {\n"
        "\tinfantry_weapons = 1\n"
        "\ttransport = 1\n"
        "}\n"
        "add_manpower = 50000\n"
        "set_politics = {\n"
        "\truling_party = democratic\n"
        '\tlast_election = "1936.1.1"\n'
        "\telection_frequency = 48\n"
        "\telections_allowed = no\n"
        "}\n"
        "set_popularities = {\n"
        "\tdemocratic = 60\n"
        "\tfascism = 10\n"
        "\tcommunism = 10\n"
        "\tneutrality = 20\n"
        "}\n"
        "set_convoys = 5000\n"
        "create_corps_commander = {\n"
        '\tname = "QAA Acceptance Commander"\n'
        "\ttraits = { }\n"
        "\tskill = 1\n"
        "\tattack_skill = 1\n"
        "\tdefense_skill = 1\n"
        "\tplanning_skill = 1\n"
        "\tlogistics_skill = 1\n"
        "}\n"
    )
    country_history = (tmp_path / "history/countries/QAA.txt").read_text(
        encoding="utf-8"
    )
    assert country_history == expected_country
    assert (tmp_path / "history/countries/QAB.txt").read_text(
        encoding="utf-8"
    ) == expected_country.replace("capital = 1", "capital = 2").replace(
        'oob = "QAA_1936"', 'oob = "QAB_1936"'
    ).replace(
        'name = "QAA Acceptance Commander"',
        'name = "QAB Acceptance Commander"',
    )
    for tag in ("QAA", "QAB"):
        tag_history = (tmp_path / f"history/countries/{tag}.txt").read_text(
            encoding="utf-8"
        )
        assert tag_history.count("set_technology = {") == 1
        assert "\ttransport = 1\n" in tag_history
    for obsolete in (
        "\telection = ",
        "majority = {",
        "set_politics = { parties =",
        "set_convoys = {",
    ):
        assert obsolete not in country_history

    expected_oob = (
        "# acceptance-only test OOB generated by the acceptance profile\n"
        "division_template = {\n"
        '\tname = "Infantry Division"\n'
        "\tregiments = {\n"
        "\t\tinfantry = { x = 0 y = 0 }\n"
        "\t\tinfantry = { x = 0 y = 1 }\n"
        "\t\tinfantry = { x = 0 y = 2 }\n"
        "\t}\n"
        "}\n\n"
        "units = {\n"
        "\tdivision = {\n"
        '\t\tname = "1st Infantry Division"\n'
        "\t\tlocation = 1\n"
        '\t\tdivision_template = "Infantry Division"\n'
        "\t\tstart_experience_factor = 0.3\n"
        "\t\tstart_equipment_factor = 1.0\n"
        "\t}\n"
        "}\n"
    )
    assert (tmp_path / "history/units/QAA_1936.txt").read_text(
        encoding="utf-8"
    ) == expected_oob
    qab_oob = (tmp_path / "history/units/QAB_1936.txt").read_text(
        encoding="utf-8"
    )
    assert qab_oob == expected_oob.replace("location = 1", "location = 2")
    assert "divisions = {" not in expected_oob

    expected_bookmark = (
        "# acceptance-only bookmark generated by the acceptance profile\n"
        "bookmarks = {\n"
        "\tbookmark = {\n"
        "\t\tname = ACCEPTANCE_TEST_BOOKMARK\n"
        "\t\tdesc = ACCEPTANCE_TEST_BOOKMARK_DESC\n"
        "\t\tdate = 1936.1.1.12\n"
        "\t\tpicture = GFX_select_date_1936\n"
        '\t\tdefault_country = "QAA"\n'
        "\t\tdefault = yes\n"
        "\n"
        '\t\t"QAA" = {\n'
        '\t\t\thistory = "QAA_BOOKMARK_DESC"\n'
        "\t\t\tideology = democratic\n"
        "\t\t}\n"
        '\t\t"QAB" = {\n'
        '\t\t\thistory = "QAB_BOOKMARK_DESC"\n'
        "\t\t\tideology = democratic\n"
        "\t\t\tminor = yes\n"
        "\t\t}\n"
        '\t\t"---" = {\n'
        "\t\t\thistory = ACCEPTANCE_TEST_OTHER_BOOKMARK_DESC\n"
        "\t\t}\n"
        "\t\teffect = {\n"
        "\t\t\trandomize_weather = 22345\n"
        "\t\t}\n"
        "\t}\n"
        "}\n"
    )
    bookmark = (tmp_path / "common/bookmarks/99_acceptance.txt").read_text(
        encoding="utf-8"
    )
    assert bookmark == expected_bookmark
    assert "randomize_weather = yes" not in bookmark
    assert 'desc = "ACCEPTANCE_QAA_DESC"' not in bookmark

    localisation = (
        tmp_path / "localisation/english/acceptance_l_english.yml"
    ).read_text(encoding="utf-8-sig")
    assert 'ACCEPTANCE_TEST_BOOKMARK:0 "Acceptance Test"' in localisation
    assert 'QAA_BOOKMARK_DESC:0 "A generated acceptance test country."' in localisation
    assert 'QAB_BOOKMARK_DESC:0 "A generated acceptance test country."' in localisation

    required_shadows = {
        "common/ai_strategy/ENG.txt",
        "common/ai_strategy/ETH.txt",
        "common/ai_strategy/FRA.txt",
        "common/ai_strategy/GER.txt",
        "common/ai_strategy/HOL.txt",
        "common/ai_strategy/INS.txt",
        "common/ai_strategy/ITA.txt",
        "common/ai_strategy/JAP.txt",
        "common/ai_strategy/ROM.txt",
        "common/ai_strategy/SOV.txt",
        "common/ai_strategy/USA.txt",
        "common/decisions/zz_tc_map_safety.txt",
        "common/ai_faction_theaters/ai_faction_theaters.txt",
        "common/on_actions/14_sea_on_actions.txt",
        "common/scripted_triggers/zz_tc_map_safety.txt",
        "events/SEA_Japan.txt",
        "tutorial/tutorial.txt",
    }
    written_paths = {entry.rel_path for entry in result.written}
    assert required_shadows <= written_paths
    assert (tmp_path / "common/ai_strategy/INS.txt").read_text(
        encoding="utf-8"
    ).startswith("# Empty - TC MOD")

    owned_files = result.owned_files
    assert "common/ai_strategy/" in owned_files
    assert "common/names/" in owned_files
    assert "common/on_actions/" in owned_files
    assert "common/names/99_acceptance_names.txt" in written_paths
    assert all(
        any(path == owned or (owned.endswith("/") and path.startswith(owned))
            for owned in owned_files)
        for path in written_paths
    )
    assert any("compatibility shadows" in note for note in result.notes)
    assert any("compatibility shadows" in item for item in context.provenance)
    assert {sid: states.get_state(sid).owner_tag for sid in (1, 2, 3)} == {
        1: "QAA",
        2: "QAB",
        3: "QAA",
    }

    deterministic_paths = (
        "common/names/99_acceptance_names.txt",
        "history/countries/QAA.txt",
        "history/countries/QAB.txt",
        "history/units/QAA_1936.txt",
        "history/units/QAB_1936.txt",
    )
    first_output = {
        rel_path: (tmp_path / rel_path).read_text(encoding="utf-8")
        for rel_path in deterministic_paths
    }
    run(context)
    assert {
        rel_path: (tmp_path / rel_path).read_text(encoding="utf-8")
        for rel_path in deterministic_paths
    } == first_output


def test_acceptance_uses_first_coastal_primary_and_keeps_other_states_with_primary(
    tmp_path,
):
    states = StateManager()
    state_provinces = {
        1: [11, 12],
        2: [21, 22],
        3: [31, 32],
        4: [41],
        5: [51],
    }
    for state_id, provinces in state_provinces.items():
        state = states.create_state()
        state.provinces = list(provinces)
        state.owner_tag = "BEL"

    context = StageContext(
        profile_name="acceptance",
        output_dir=str(tmp_path),
        state_mgr=states,
        acceptance_tags=("QAA", "QAB", "QAC"),
        scratch={
            "states": state_provinces,
            "coastal_set": {32, 42},
        },
    )

    run(context)

    country_dir = tmp_path / "history/countries"
    unit_dir = tmp_path / "history/units"
    assert "capital = 3\n" in (country_dir / "QAA.txt").read_text(encoding="utf-8")
    assert "capital = 1\n" in (country_dir / "QAB.txt").read_text(encoding="utf-8")
    assert "capital = 2\n" in (country_dir / "QAC.txt").read_text(encoding="utf-8")
    assert "location = 32\n" in (unit_dir / "QAA_1936.txt").read_text(encoding="utf-8")
    assert "location = 11\n" in (unit_dir / "QAB_1936.txt").read_text(encoding="utf-8")
    assert "location = 21\n" in (unit_dir / "QAC_1936.txt").read_text(encoding="utf-8")
    assert {sid: states.get_state(sid).owner_tag for sid in state_provinces} == {
        1: "QAB",
        2: "QAC",
        3: "QAA",
        4: "QAA",
        5: "QAA",
    }

    assert sorted(path.name for path in unit_dir.iterdir()) == [
        "QAA_1936.txt",
        "QAB_1936.txt",
        "QAC_1936.txt",
    ]
    for unit_file in unit_dir.iterdir():
        unit_text = unit_file.read_text(encoding="utf-8")
        assert "fleet =" not in unit_text
        assert "ship =" not in unit_text
