"""Acceptance content stage: deterministic test tags on the foundation (M2.4/M2.5)."""
from __future__ import annotations

import os

from export.stages.base import record_written, snapshot_output_files


NAME = "acceptance_content"
OWNED_FILES = (
    "common/country_tags/99_acceptance_tags.txt",
    "common/countries/",
    "common/names/",
    "history/countries/",
    "history/units/",
    "common/bookmarks/99_acceptance.txt",
    "localisation/english/acceptance_l_english.yml",
    "common/ai_strategy/",
    "common/decisions/",
    "common/ai_faction_theaters/",
    "common/on_actions/",
    "common/scripted_triggers/",
    "events/",
    "tutorial/tutorial.txt",
)
PROFILES = ("acceptance",)
REQUIRES = ("states",)
PROVIDES = ("acceptance_tags",)

_ACCEPTANCE_MALE_NAMES = (
    "John", "Bob", "Lucas", "Marcus", "Alexander", "Alex", "Peter", "Jonas", "Jim", "Johannes",
)
_ACCEPTANCE_FEMALE_NAMES = (
    "Juliette", "Anna", "Jessica", "Emma", "Hanna", "Sofia", "Marie", "Hildegard",
)
_ACCEPTANCE_SURNAMES = (
    "Smith", "Jones", "Taylor", "Brown", "Williams", "Wilson", "Evans", "Walker", "White", "Roberts",
)
_ACCEPTANCE_CALLSIGNS = (
    "Easy Kill", "The Lightning", "The Devil", "Grasshopper", "Handsome", "Moose", "Mouse", "Pebbles",
    "Sunshine", "Demon",
)


def _acceptance_names_text(tags: list[str]) -> str:
    """Return complete deterministic character and generic operation name pools."""
    def quoted(values: tuple[str, ...]) -> str:
        return " ".join('"%s"' % value for value in values)

    lines = ["# acceptance-only character and operation name pools generated by the acceptance profile"]
    for tag in tags:
        lines.extend((
            "%s = {" % tag,
            "\tmale = {",
            "\t\tnames = { %s }" % quoted(_ACCEPTANCE_MALE_NAMES),
            "\t\tsurnames = { }",
            "\t\tcallsigns = { }",
            "\t}",
            "\tfemale = {",
            "\t\tnames = { %s }" % quoted(_ACCEPTANCE_FEMALE_NAMES),
            "\t\tsurnames = { }",
            "\t\tcallsigns = { }",
            "\t}",
            "\tsurnames = { %s }" % quoted(_ACCEPTANCE_SURNAMES),
            "\tcallsigns = { %s }" % quoted(_ACCEPTANCE_CALLSIGNS),
            "\tprefix = o_operation",
            "\toperation = {",
            "\t\t0 = { o_default_operation }",
            "\t}",
            "\tuse_geographical_default_operation_names = yes",
            "\toffensive_operation_suffix = o_strat_offensive_default",
            "\tdefensive_operation_suffix = o_strat_defensive_default",
            "\tnaval_operation_suffix = o_strat_naval_default",
            "}",
            "",
        ))
    return "\n".join(lines).rstrip() + "\n"


def _acceptance_country_text(tag: str, capital_state: int, oob: str) -> str:
    return (
        "# acceptance-only test content generated by the acceptance profile\n"
        "capital = %d\n"
        "oob = \"%s\"\n"
        "set_research_slots = 3\n"
        "load_focus_tree = generic_focus\n"
        "set_technology = {\n"
        "\tinfantry_weapons = 1\n"
        "\ttransport = 1\n"
        "}\n"
        "add_manpower = 50000\n"
        "set_politics = {\n"
        "\truling_party = democratic\n"
        "\tlast_election = \"1936.1.1\"\n"
        "\telection_frequency = 48\n"
        "\telections_allowed = no\n"
        "}\n"
        "set_popularities = {\n"
        "\tdemocratic = 60\n"
        "\tfascism = 10\n"
        "\tcommunism = 10\n"
        "\tneutrality = 20\n"
        "}\n"
        "set_convoys = 5000\n"
        "create_corps_commander = {\n"
        "\tname = \"%s Acceptance Commander\"\n"
        "\ttraits = { }\n"
        "\tskill = 1\n"
        "\tattack_skill = 1\n"
        "\tdefense_skill = 1\n"
        "\tplanning_skill = 1\n"
        "\tlogistics_skill = 1\n"
        "}\n" % (capital_state, oob, tag)
    )


def _acceptance_country_definition_text(tag: str, index: int) -> str:
    """Return the minimal country definition required by a test tag."""

    # Keep colors distinct and deterministic without depending on project
    # ownership or the vanilla country database.
    red = (index * 67) % 180 + 40
    green = (index * 101) % 180 + 40
    blue = (index * 149) % 180 + 40
    return (
        "# acceptance-only country definition generated by the acceptance profile\n"
        "graphical_culture = western_european_gfx\n"
        "graphical_culture_2d = western_european_2d\n"
        "color = { %d %d %d }\n"
        % (red, green, blue)
    )


def _acceptance_oob_text(capital_province: int) -> str:
    return (
        "# acceptance-only test OOB generated by the acceptance profile\n"
        "division_template = {\n"
        "\tname = \"Infantry Division\"\n"
        "\tregiments = {\n"
        "\t\tinfantry = { x = 0 y = 0 }\n"
        "\t\tinfantry = { x = 0 y = 1 }\n"
        "\t\tinfantry = { x = 0 y = 2 }\n"
        "\t}\n"
        "}\n\n"
        "units = {\n"
        "\tdivision = {\n"
        "\t\tname = \"1st Infantry Division\"\n"
        "\t\tlocation = %d\n"
        "\t\tdivision_template = \"Infantry Division\"\n"
        "\t\tstart_experience_factor = 0.3\n"
        "\t\tstart_equipment_factor = 1.0\n"
        "\t}\n"
        "}\n" % capital_province
    )


def run(ctx):
    from domain.export_contract import RESERVED_ACCEPTANCE_TAGS, StageResult
    before = snapshot_output_files(ctx.output_dir)
    notes: list = []
    tags = [str(t).upper() for t in (ctx.acceptance_tags or ())]
    for tag in tags:
        if tag in set(RESERVED_ACCEPTANCE_TAGS):
            raise ValueError("acceptance tag %s is reserved and must never be generated" % tag)
    occupied = set()
    if ctx.country_mgr is not None:
        occupied.update(str(t).upper() for t in (getattr(ctx.country_mgr, "countries", {}) or {}))
    for tag in tags:
        if tag in occupied:
            raise ValueError("acceptance tag %s collides with an occupied tag" % tag)
    if ctx.enabled("replace_path"):
        from export.writers.replace_path.scrubber import write_ai_strategy_overrides

        write_ai_strategy_overrides(ctx.output_dir)
        message = (
            "acceptance profile includes narrow custom-map AI and safety compatibility shadows"
        )
        notes.append(message)
        ctx.provenance.append(message)
    if not tags:
        notes.append("no acceptance tags planned; acceptance content skipped")
        return StageResult(stage=NAME, owned_files=OWNED_FILES, written=record_written(ctx, before),
                           notes=notes)
    content_enabled = ctx.enabled("countries")
    localisation_enabled = ctx.enabled("localisation")
    if not content_enabled and not localisation_enabled:
        notes.append("countries and localisation layers disabled by scope; acceptance files skipped")
        return StageResult(stage=NAME, owned_files=OWNED_FILES, written=record_written(ctx, before),
                           notes=notes)
    states = ctx.scratch.get("states") or {}
    state_ids = sorted(states)
    coastal_set = {int(province) for province in (ctx.scratch.get("coastal_set") or ())}
    if not content_enabled:
        assignments = {}
        notes.append("country layer disabled; acceptance tags are retained only in the plan")
    elif not state_ids:
        notes.append("no states available for test ownership; tags recorded without owners")
        assignments = {}
    else:
        primary_state = next(
            (
                sid for sid in state_ids
                if any(int(province) in coastal_set for province in (states.get(sid) or ()))
            ),
            state_ids[0],
        )
        assignments = {tags[0]: primary_state}
        selected_capitals = {primary_state}
        for tag in tags[1:]:
            fallback_state = next(
                (sid for sid in state_ids if sid not in selected_capitals), primary_state
            )
            assignments[tag] = fallback_state
            selected_capitals.add(fallback_state)
        owner_by_state = {primary_state: tags[0]}
        for tag in tags[1:]:
            owner_by_state.setdefault(assignments[tag], tag)
        if ctx.state_mgr is not None and hasattr(ctx.state_mgr, "get_state"):
            # The acceptance artifact replaces state and country histories, so
            # every emitted state must use one of the generated tags. Leaving
            # project owners such as BEL/FRA behind would reference histories
            # that are intentionally absent from this isolated artifact.
            for sid in state_ids:
                state = ctx.state_mgr.get_state(sid)
                if state is None:
                    continue
                owner_tag = owner_by_state.get(sid, tags[0])
                state.owner_tag = owner_tag
                ctx.placeholders.append({"state": int(sid), "field": "owner",
                                         "note": "acceptance-only test owner %s" % owner_tag,
                                         "profile": "acceptance"})
        ctx.provenance.append("acceptance test owners %s assigned to states %s (working copy only)"
                              % (", ".join(tags), ", ".join(str(s) for s in sorted(set(assignments.values())))))
    if content_enabled:
        tags_dir = os.path.join(ctx.output_dir, "common", "country_tags")
        os.makedirs(tags_dir, exist_ok=True)
        with open(os.path.join(tags_dir, "99_acceptance_tags.txt"), "w", encoding="utf-8") as handle:
            handle.write("# acceptance-only test tags generated by the acceptance profile\n")
            for tag in tags:
                handle.write("%s = \"countries/%s.txt\"\n" % (tag, tag))
        countries_dir = os.path.join(ctx.output_dir, "common", "countries")
        os.makedirs(countries_dir, exist_ok=True)
        for index, tag in enumerate(tags, 1):
            with open(os.path.join(countries_dir, "%s.txt" % tag), "w", encoding="utf-8") as handle:
                handle.write(_acceptance_country_definition_text(tag, index))
        names_dir = os.path.join(ctx.output_dir, "common", "names")
        os.makedirs(names_dir, exist_ok=True)
        with open(os.path.join(names_dir, "99_acceptance_names.txt"), "w", encoding="utf-8") as handle:
            handle.write(_acceptance_names_text(tags))
        countries_dir = os.path.join(ctx.output_dir, "history", "countries")
        os.makedirs(countries_dir, exist_ok=True)
        units_dir = os.path.join(ctx.output_dir, "history", "units")
        os.makedirs(units_dir, exist_ok=True)
        for tag in tags:
            capital_state = int(assignments.get(tag, state_ids[0] if state_ids else 1))
            state_provinces = sorted(
                int(province) for province in (states.get(capital_state) or ())
            )
            coastal_provinces = [province for province in state_provinces
                                 if province in coastal_set]
            if tag == tags[0] and coastal_provinces:
                capital_province = coastal_provinces[0]
            else:
                capital_province = state_provinces[0] if state_provinces else capital_state
            with open(os.path.join(countries_dir, "%s.txt" % tag),
                      "w", encoding="utf-8") as handle:
                handle.write(_acceptance_country_text(tag, capital_state, "%s_1936" % tag))
            with open(os.path.join(units_dir, "%s_1936.txt" % tag),
                      "w", encoding="utf-8") as handle:
                handle.write(_acceptance_oob_text(capital_province))
        bookmarks_dir = os.path.join(ctx.output_dir, "common", "bookmarks")
        os.makedirs(bookmarks_dir, exist_ok=True)
        with open(os.path.join(bookmarks_dir, "99_acceptance.txt"), "w", encoding="utf-8") as handle:
            handle.write("# acceptance-only bookmark generated by the acceptance profile\n")
            handle.write(
                "bookmarks = {\n"
                "\tbookmark = {\n"
                "\t\tname = ACCEPTANCE_TEST_BOOKMARK\n"
                "\t\tdesc = ACCEPTANCE_TEST_BOOKMARK_DESC\n"
                "\t\tdate = 1936.1.1.12\n"
                "\t\tpicture = GFX_select_date_1936\n"
                "\t\tdefault_country = \"%s\"\n" % tags[0]
            )
            handle.write("\t\tdefault = yes\n\n")
            for index, tag in enumerate(tags):
                handle.write("\t\t\"%s\" = {\n" % tag)
                handle.write("\t\t\thistory = \"%s_BOOKMARK_DESC\"\n" % tag)
                handle.write("\t\t\tideology = democratic\n")
                if index:
                    handle.write("\t\t\tminor = yes\n")
                handle.write("\t\t}\n")
            handle.write(
                "\t\t\"---\" = {\n"
                "\t\t\thistory = ACCEPTANCE_TEST_OTHER_BOOKMARK_DESC\n"
                "\t\t}\n"
                "\t\teffect = {\n"
                "\t\t\trandomize_weather = 22345\n"
                "\t\t}\n"
            )
            handle.write("\t}\n}\n")
    if localisation_enabled:
        loc_dir = os.path.join(ctx.output_dir, "localisation", "english")
        os.makedirs(loc_dir, exist_ok=True)
        with open(os.path.join(loc_dir, "acceptance_l_english.yml"), "w", encoding="utf-8") as handle:
            handle.write("\ufeffl_english:\n")
            handle.write(' ACCEPTANCE_TEST_BOOKMARK:0 "Acceptance Test"\n')
            handle.write(
                ' ACCEPTANCE_TEST_BOOKMARK_DESC:0 "A minimal test scenario for a custom map."\n'
            )
            handle.write(
                ' ACCEPTANCE_TEST_OTHER_BOOKMARK_DESC:0 "Other acceptance test countries"\n'
            )
            for tag in tags:
                handle.write(" %s:0 \"Acceptance Test %s\"\n" % (tag, tag))
                handle.write(
                    ' %s_BOOKMARK_DESC:0 "A generated acceptance test country."\n' % tag
                )
    notes.append("acceptance tags: %s" % ", ".join(tags))
    ctx.scratch["acceptance_tags"] = list(tags)
    written = record_written(ctx, before)
    return StageResult(stage=NAME, owned_files=OWNED_FILES, written=written, notes=notes)
