"""Acceptance content stage: deterministic test tags on the foundation (M2.4/M2.5)."""
from __future__ import annotations

import os

from export.stages.base import record_written, snapshot_output_files


NAME = "acceptance_content"
OWNED_FILES = (
    "common/country_tags/99_acceptance_tags.txt",
    "history/countries/",
    "history/units/",
    "common/bookmarks/99_acceptance.txt",
    "localisation/english/acceptance_l_english.yml",
)
PROFILES = ("acceptance",)
REQUIRES = ("states",)
PROVIDES = ("acceptance_tags",)


def _acceptance_country_text(tag: str, name: str, capital_state: int, oob: str) -> str:
    return (
        "# acceptance-only test content generated by the acceptance profile\n"
        "capital = %d\n"
        "oob = \"%s\"\n"
        "set_research_slots = 3\n"
        "%s = {\n"
        "\tlast_election = \"1936.1.1\"\n"
        "\telection = \"1940.1.1\"\n"
        "\truling_party = democratic\n"
        "\tmajority = { democratic = 60 fascism = 10 communism = 10 neutrality = 20 }\n"
        "}\n"
        "set_politics = { parties = { democratic = { popularity = 60 } } }\n"
        "set_convoys = { value = 50 }\n" % (capital_state, oob, tag)
    )


def _acceptance_oob_text(tag: str, capital_province: int) -> str:
    return (
        "# acceptance-only test OOB generated by the acceptance profile\n"
        "divisions = {\n"
        "\t%s_Test_Division = {\n"
        "\t\tdivision_template = \"Test Infantry\"\n"
        "\t\tstart_experience_factor = 0.2\n"
        "\t\tstart_equipment_factor = 0.5\n"
        "\t}\n"
        "}\n"
        "units = {\n"
        "\t%s_Test_Division = { location = %d }\n"
        "}\n" % (tag, tag, capital_province)
    )


def run(ctx):
    from domain.export_contract import RESERVED_ACCEPTANCE_TAGS, StageResult
    before = snapshot_output_files(ctx.output_dir)
    notes: list = []
    tags = [str(t).upper() for t in (ctx.acceptance_tags or ())]
    if not tags:
        notes.append("no acceptance tags planned; acceptance content skipped")
        return StageResult(stage=NAME, owned_files=OWNED_FILES, written=record_written(ctx, before),
                           notes=notes)
    for tag in tags:
        if tag in set(RESERVED_ACCEPTANCE_TAGS):
            raise ValueError("acceptance tag %s is reserved and must never be generated" % tag)
    occupied = set()
    if ctx.country_mgr is not None:
        occupied.update(str(t).upper() for t in (getattr(ctx.country_mgr, "countries", {}) or {}))
    for tag in tags:
        if tag in occupied:
            raise ValueError("acceptance tag %s collides with an occupied tag" % tag)
    content_enabled = ctx.enabled("countries")
    localisation_enabled = ctx.enabled("localisation")
    if not content_enabled and not localisation_enabled:
        notes.append("countries and localisation layers disabled by scope; acceptance files skipped")
        return StageResult(stage=NAME, owned_files=OWNED_FILES, written=record_written(ctx, before),
                           notes=notes)
    states = ctx.scratch.get("states") or {}
    state_ids = sorted(states)
    if not content_enabled:
        assignments = {}
        notes.append("country layer disabled; acceptance tags are retained only in the plan")
    elif not state_ids:
        notes.append("no states available for test ownership; tags recorded without owners")
        assignments = {}
    else:
        assignments = {tag: state_ids[index % len(state_ids)] for index, tag in enumerate(tags)}
        for tag, sid in assignments.items():
            state = None
            if ctx.state_mgr is not None and hasattr(ctx.state_mgr, "get_state"):
                state = ctx.state_mgr.get_state(sid)
            if state is not None:
                state.owner_tag = tag
                ctx.placeholders.append({"state": int(sid), "field": "owner",
                                         "note": "acceptance-only test owner %s" % tag,
                                         "profile": "acceptance"})
        ctx.provenance.append("acceptance test owners %s assigned to states %s (working copy only)"
                              % (", ".join(tags), ", ".join(str(s) for s in sorted(set(assignments.values())))))
    if content_enabled:
        tags_dir = os.path.join(ctx.output_dir, "common", "country_tags")
        os.makedirs(tags_dir, exist_ok=True)
        with open(os.path.join(tags_dir, "99_acceptance_tags.txt"), "w", encoding="utf-8") as handle:
            handle.write("# acceptance-only test tags generated by the acceptance profile\n")
            for tag in tags:
                handle.write("%s = \"countries/%s - Acceptance Test.txt\"\n" % (tag, tag))
        countries_dir = os.path.join(ctx.output_dir, "history", "countries")
        os.makedirs(countries_dir, exist_ok=True)
        units_dir = os.path.join(ctx.output_dir, "history", "units")
        os.makedirs(units_dir, exist_ok=True)
        for tag in tags:
            capital_state = int(assignments.get(tag, state_ids[0] if state_ids else 1))
            capital_province = capital_state
            if states and capital_state in states and states[capital_state]:
                capital_province = int(states[capital_state][0])
            with open(os.path.join(countries_dir, "%s - Acceptance Test.txt" % tag),
                      "w", encoding="utf-8") as handle:
                handle.write(_acceptance_country_text(tag, "Acceptance Test %s" % tag,
                                                      capital_state, "%s_Acceptance_OOB" % tag))
            with open(os.path.join(units_dir, "%s_Acceptance_OOB.txt" % tag),
                      "w", encoding="utf-8") as handle:
                handle.write(_acceptance_oob_text(tag, capital_province))
        bookmarks_dir = os.path.join(ctx.output_dir, "common", "bookmarks")
        os.makedirs(bookmarks_dir, exist_ok=True)
        with open(os.path.join(bookmarks_dir, "99_acceptance.txt"), "w", encoding="utf-8") as handle:
            handle.write("# acceptance-only bookmark generated by the acceptance profile\n")
            handle.write("bookmarks = {\n\tbookmark = {\n\t\tname = \"ACCEPTANCE_TEST\"\n")
            handle.write("\t\tdate = 1936.1.1\n\t\tdefault_country = \"%s\"\n" % tags[0])
            for tag in tags:
                handle.write("\t\t%s = { desc = \"ACCEPTANCE_%s_DESC\" }\n" % (tag, tag))
            handle.write("\t}\n}\n")
    if localisation_enabled:
        loc_dir = os.path.join(ctx.output_dir, "localisation", "english")
        os.makedirs(loc_dir, exist_ok=True)
        with open(os.path.join(loc_dir, "acceptance_l_english.yml"), "w", encoding="utf-8") as handle:
            handle.write("\ufeffl_english:\n")
            for tag in tags:
                handle.write(" %s:0 \"Acceptance Test %s\"\n" % (tag, tag))
    notes.append("acceptance tags: %s" % ", ".join(tags))
    ctx.scratch["acceptance_tags"] = list(tags)
    written = record_written(ctx, before)
    return StageResult(stage=NAME, owned_files=OWNED_FILES, written=written, notes=notes)
