"""Scaffold content stage: generated gameplay helpers with provenance (M2.4/M2.5)."""
from __future__ import annotations

import json
import os

import numpy as np

from export.stages.base import record_written, snapshot_output_files


NAME = "scaffold_content"
OWNED_FILES = (
    "history/countries/",
    "common/country_tags/",
    "common/countries/",
    "common/characters/",
    "common/units/",
    "common/ideas/",
    "common/names/",
    "history/units/",
    "common/bookmarks/",
    "localisation/",
    "gfx/flags/",
    "common/defines/",
    "common/ai_strategy/",
    "common/ai_strategy_plans/",
    "common/ai_faction_theaters/",
    "common/decisions/",
    "common/on_actions/",
    "common/scripted_triggers/",
    "events/",
    "tutorial/",
    "history/general/",
    "portraits/",
    "scaffold_provenance.json",
)
PROFILES = ("scaffold", "legacy_full")
REQUIRES = ("states",)
PROVIDES = ()


def run(ctx):
    from domain.export_contract import StageResult
    before = snapshot_output_files(ctx.output_dir)
    notes: list = []
    if ctx.profile_name == "scaffold" and ctx.state_mgr is not None \
            and getattr(ctx.state_mgr, "states", None):
        from services.export_service import fill_default_state_data
        filled = fill_default_state_data(
            ctx.state_mgr,
            np.asarray(ctx.terrain_map) if ctx.terrain_map is not None else None,
            np.asarray(ctx.province_map),
            np.asarray(ctx.tile_map),
        )
        if filled:
            message = ("filled default resources/buildings/manpower for %d states as generated "
                       "scaffold helpers, excluded from the foundation lock" % filled)
            notes.append(message)
            ctx.provenance.append(message)
    states = ctx.scratch.get("states")
    if ctx.enabled("countries"):
        from export.mod_exporter import _write_bookmark, _write_countries_from_mgr, _write_country
        if ctx.country_mgr is not None and getattr(ctx.country_mgr, "countries", None):
            _write_countries_from_mgr(ctx.country_mgr, ctx.output_dir, states)
            notes.append("countries from manager (dynamic D01-D75, leaders, OOBs included)")
        else:
            first_state_id = min(states.keys()) if states else 1
            _write_country(ctx.tag, first_state_id, ctx.output_dir)
            notes.append("fallback country %s" % ctx.tag)
    if ctx.enabled("gfx"):
        from export.mod_exporter import _write_country_flags
        tags = list(ctx.country_mgr.countries.keys()) \
            if ctx.country_mgr is not None and getattr(ctx.country_mgr, "countries", None) else [ctx.tag]
        _write_country_flags(tags, ctx.output_dir, ctx.country_mgr)
    if ctx.enabled("localisation"):
        from export.mod_exporter import _write_localisation_full
        region_list = ctx.scratch.get("region_list")
        from export.mod_exporter import _write_localisation_full as _loc
        _loc(ctx.mod_name, ctx.state_mgr, ctx.country_mgr, states, ctx.output_dir,
             region_count=len(region_list) if region_list else 24,
             region_mgr=ctx.strategic_region_mgr)
    if ctx.enabled("countries"):
        from export.mod_exporter import _write_bookmark
        tags = list(ctx.country_mgr.countries.keys()) \
            if ctx.country_mgr is not None and getattr(ctx.country_mgr, "countries", None) else [ctx.tag]
        _write_bookmark(ctx.mod_name, tags, ctx.output_dir)
    from export.writers.common.defines import write_defines_lua
    write_defines_lua(ctx.output_dir, province_count=int(ctx.scratch.get("province_count") or 0))
    if ctx.enabled("replace_path"):
        from export.writers.replace_path.scrubber import (
            write_ai_strategy_overrides,
            write_replace_path_dirs,
        )
        write_replace_path_dirs(ctx.output_dir)
        write_ai_strategy_overrides(ctx.output_dir)
    if ctx.profile_name == "scaffold":
        provenance_path = os.path.join(ctx.output_dir, "scaffold_provenance.json")
        payload = {
            "profile": "scaffold",
            "note": "Gameplay helpers generated by the scaffold profile; excluded from the foundation lock.",
            "generated": sorted(snapshot_output_files(ctx.output_dir) - before),
        }
        with open(provenance_path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2)
        ctx.provenance.append("scaffold helpers labelled in scaffold_provenance.json")
    written = record_written(ctx, before)
    return StageResult(stage=NAME, owned_files=OWNED_FILES, written=written, notes=notes)